package main

import "bytes"

const (
	deployScript = `#!/usr/bin/env bash
# Generated by Terraless Organisation Roles - generateDeployScript
terraform init
terraform plan -out terraform.plan -input=false

read -p "Deploy? " choice
echo
echo ${choice}

if [[ ${choice} =~ ^[Yy]$ ]]
then
	echo "Deploying..."
	terraform apply -input=false terraform.plan
else
	echo "ok, not deploying..."
fi

`
)

func generateDeployScript(config *OrganisationRolesConfig) bytes.Buffer {
	buffer := bytes.Buffer{}
	buffer = renderToBuffer(config, deployScript, "deploy-script", buffer)

	return buffer
}
