package main

import (
	"bytes"
	"fmt"
	"sort"
)

const (
	iamGroupTemplate = `
resource "aws_iam_group" "group-{{ .Name }}" {
  name = "{{ .Name }}"
}
`

	iamGroupPolicyAttachment = `
resource "aws_iam_group_policy_attachment" "group-{{ .Name }}-a-{{ .Idx }}" {
  group      = aws_iam_group.group-{{ .Name }}.name
  policy_arn = "{{ .Policy }}"
}
`

	iamGroupAssume = `
data "aws_iam_policy_document" "allow-assume-{{ .Name }}" {
  statement {
    effect = "Allow"

    actions = ["sts:AssumeRole"]

    resources = [
      {{ range $key, $val := .Arns }}"{{ $val }}",
      {{ end -}}
    ]

    condition {
      test = "Bool"
      values = ["true"]
      variable = "aws:MultiFactorAuthPresent"
    }
  }
}

resource "aws_iam_policy" "allow-assume-{{ .Name }}" {
  name = "allow-assume-{{ .Name }}"
  policy = data.aws_iam_policy_document.allow-assume-{{ .Name }}.json
}

resource "aws_iam_group_policy_attachment" "allow-assume-{{ .Name }}" {
  group      = aws_iam_group.group-{{ .Name }}.name
  policy_arn = aws_iam_policy.allow-assume-{{ .Name }}.arn
}
`
)

func generateMainAccountGroups(config *OrganisationRolesConfig) bytes.Buffer {
	buffer := bytes.Buffer{}

	buffer.WriteString("# Generated by Terraless Organisation Roles - generateMainAccountGroups")

	for _, groupName := range sortedGroupKeys(config.Groups) {
		groupData := config.Groups[groupName]
		var data = map[string]interface{}{
			"Name":            groupName,
			"ManagedPolicies": groupData.ManagedPolicies,
		}
		buffer = renderToBuffer(data, iamGroupTemplate, "iam-group", buffer)

		for idx, policy := range groupData.ManagedPolicies {
			data = map[string]interface{} {
				"Name":   groupName,
				"Idx":    idx,
				"Policy": policy,
				"Arns": buildArns(config.Accounts, groupName),
			}

			buffer = renderToBuffer(data, iamGroupPolicyAttachment, "iam_group_policy_attachment", buffer)
			buffer = renderToBuffer(data, iamGroupAssume, "iam_group_assume", buffer)
		}
	}

	return buffer
}

func buildArns(accounts map[string]Account, role string) []string {
	var result []string

	for _, accountName := range sortedAccountKeys(accounts) {
		accountData := accounts[accountName]
		result = append(result, fmt.Sprintf("arn:aws:iam::%s:role/%s", accountData.AccountId, role))
	}

	return result
}

func sortedGroupKeys(groups map[string]Group) []string {
	var keys []string
	for k := range groups {
		keys = append(keys, k)
	}

	sort.Strings(keys)

	return keys
}

func sortedAccountKeys(accounts map[string]Account) []string {
	var keys []string
	for k := range accounts {
		keys = append(keys, k)
	}

	sort.Strings(keys)

	return keys
}
