package main

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestMainAccountUsers_generateMainAccountUsers(t *testing.T) {
	// given
	config := OrganisationRolesConfig{
		Users: map[string]User{
			"dummy": {
				Groups: []string{
					"dummyGroup1",
					"dummyGroup2",
				},
			},
		},
	}

	// when
	result := generateMainAccountUsers(&config)

	// then
	expectedResult := `# Generated by Terraless Organisation Roles - generateMainAccountUsers
resource "aws_iam_user" "dummy" {
  name = "dummy"

  tags = {
    company-user = "dummy"
		ManagedBy = "Terraless AWS Organisation Roles"
  }
}

resource "aws_iam_user_group_membership" "user-group-dummy" {
  user = aws_iam_user.dummy.name
  groups = [
    aws_iam_group.group-dummyGroup1.name,
    aws_iam_group.group-dummyGroup2.name,
    ]
}
`

	assert.Equal(t, expectedResult, result.String())
}
