package main

import "bytes"

const (
	moduleCallTemplate = `
module "account-{{ .Name }}" {
	source = "./account"

	root-account-id = var.root-account-id

  providers = {
		aws = aws.{{ .Name }}
	}
}
`
)

func generateModuleCall(config *OrganisationRolesConfig) bytes.Buffer {
	buffer := bytes.Buffer{}
	buffer.WriteString("# Generated by Terraless Organisation Roles - generateModuleCall")

	for accountName, accountData := range config.Accounts {
		var data = map[string]interface{}{
			"Name": accountName,
			"Data": accountData,
		}
		buffer = renderToBuffer(data, moduleCallTemplate, "module-call", buffer)
	}

	return buffer
}
